/**
 * Curated D1 program seed lists for the blog generator's college-rotation
 * queue. Each sport gets its own list — the generator pulls
 * SCHOOLS[sport][cron_state.college_queue_index % SCHOOLS[sport].length]
 * each "college day" so every sport sees a different school per day and the
 * lists cycle independently.
 *
 * These are starter lists. Once the full school database is wired in,
 * replace `getCollegeForSport()` with a query against that source.
 */

import type { SportSlug } from './blog/posts'

interface College {
  name: string
}

// Top D1 men's + women's soccer programs (mixed sample across conferences).
const SOCCER_D1: College[] = [
  { name: 'Stanford University' },
  { name: 'University of California, Los Angeles' },
  { name: 'University of North Carolina at Chapel Hill' },
  { name: 'University of Notre Dame' },
  { name: 'Duke University' },
  { name: 'University of Virginia' },
  { name: 'Wake Forest University' },
  { name: 'Indiana University' },
  { name: 'University of Maryland' },
  { name: 'Georgetown University' },
  { name: 'Pennsylvania State University' },
  { name: 'Florida State University' },
  { name: 'University of Central Florida' },
  { name: 'University of Georgia' },
  { name: 'Vanderbilt University' },
  { name: 'University of Southern California' },
  { name: 'University of California, Berkeley' },
  { name: 'University of Washington' },
  { name: 'San Diego State University' },
  { name: 'Saint Louis University' },
  { name: 'Creighton University' },
  { name: 'Marquette University' },
  { name: 'Loyola Marymount University' },
  { name: 'University of Connecticut' },
  { name: 'Boston College' },
  { name: 'Syracuse University' },
  { name: 'University of Pittsburgh' },
  { name: 'University of Louisville' },
  { name: 'North Carolina State University' },
  { name: 'Clemson University' },
  { name: 'Virginia Tech' },
  { name: 'Brigham Young University' },
  { name: 'University of Texas at Austin' },
  { name: 'Texas Tech University' },
  { name: 'University of Michigan' },
  { name: 'Michigan State University' },
  { name: 'The Ohio State University' },
  { name: 'University of Wisconsin–Madison' },
  { name: 'Northwestern University' },
  { name: 'Rutgers University' },
  { name: 'Princeton University' },
  { name: 'Harvard University' },
  { name: 'Yale University' },
  { name: 'Brown University' },
  { name: 'Columbia University' },
  { name: 'Dartmouth College' },
  { name: 'Cornell University' },
  { name: 'University of Denver' },
  { name: 'University of Portland' },
  { name: 'Gonzaga University' },
]

const BASKETBALL_D1: College[] = [
  { name: 'Duke University' },
  { name: 'University of North Carolina at Chapel Hill' },
  { name: 'University of Kentucky' },
  { name: 'University of Kansas' },
  { name: 'University of California, Los Angeles' },
  { name: 'Michigan State University' },
  { name: 'Villanova University' },
  { name: 'University of Arizona' },
  { name: 'Gonzaga University' },
  { name: 'Indiana University' },
  { name: 'University of Louisville' },
  { name: 'University of Connecticut' },
  { name: 'Syracuse University' },
  { name: 'University of Florida' },
  { name: 'University of Texas at Austin' },
  { name: 'University of Michigan' },
  { name: 'University of Maryland' },
  { name: 'Georgetown University' },
  { name: 'University of Memphis' },
  { name: 'University of Cincinnati' },
  { name: 'Marquette University' },
  { name: 'University of Wisconsin–Madison' },
  { name: 'The Ohio State University' },
  { name: 'Purdue University' },
  { name: 'University of Illinois at Urbana-Champaign' },
  { name: 'University of Iowa' },
  { name: 'University of Minnesota' },
  { name: 'Northwestern University' },
  { name: 'Pennsylvania State University' },
  { name: 'Rutgers University' },
  { name: 'University of Nebraska–Lincoln' },
  { name: 'University of Notre Dame' },
  { name: 'University of Virginia' },
  { name: 'Virginia Tech' },
  { name: 'University of Miami' },
  { name: 'University of Pittsburgh' },
  { name: 'North Carolina State University' },
  { name: 'Wake Forest University' },
  { name: 'Boston College' },
  { name: 'Clemson University' },
  { name: 'Florida State University' },
  { name: 'Georgia Institute of Technology' },
  { name: 'University of Tennessee' },
  { name: 'University of Alabama' },
  { name: 'Auburn University' },
  { name: 'University of Arkansas' },
  { name: 'Louisiana State University' },
  { name: 'Mississippi State University' },
  { name: 'University of Mississippi' },
  { name: 'University of Missouri' },
  { name: 'University of South Carolina' },
  { name: 'Texas A&M University' },
  { name: 'Vanderbilt University' },
  { name: 'Baylor University' },
  { name: 'Iowa State University' },
  { name: 'Kansas State University' },
  { name: 'University of Oklahoma' },
  { name: 'Oklahoma State University' },
  { name: 'Texas Christian University' },
  { name: 'Texas Tech University' },
  { name: 'West Virginia University' },
  { name: 'University of Houston' },
  { name: "Saint Mary's College of California" },
  { name: 'Brigham Young University' },
  { name: 'Stanford University' },
  { name: 'University of Southern California' },
  { name: 'University of Oregon' },
  { name: 'University of Washington' },
  { name: 'University of California, Berkeley' },
  { name: 'University of Colorado Boulder' },
  { name: 'University of Utah' },
]

const FOOTBALL_D1: College[] = [
  { name: 'University of Alabama' },
  { name: 'University of Georgia' },
  { name: 'The Ohio State University' },
  { name: 'University of Michigan' },
  { name: 'University of Texas at Austin' },
  { name: 'University of Oklahoma' },
  { name: 'University of Southern California' },
  { name: 'University of Notre Dame' },
  { name: 'Pennsylvania State University' },
  { name: 'Louisiana State University' },
  { name: 'University of Florida' },
  { name: 'University of Tennessee' },
  { name: 'Auburn University' },
  { name: 'Clemson University' },
  { name: 'Florida State University' },
  { name: 'University of Miami' },
  { name: 'University of North Carolina at Chapel Hill' },
  { name: 'North Carolina State University' },
  { name: 'Virginia Tech' },
  { name: 'University of Virginia' },
  { name: 'University of Pittsburgh' },
  { name: 'Boston College' },
  { name: 'Syracuse University' },
  { name: 'Wake Forest University' },
  { name: 'Duke University' },
  { name: 'University of Louisville' },
  { name: 'Indiana University' },
  { name: 'University of Iowa' },
  { name: 'Iowa State University' },
  { name: 'Kansas State University' },
  { name: 'University of Kansas' },
  { name: 'University of Minnesota' },
  { name: 'University of Wisconsin–Madison' },
  { name: 'University of Nebraska–Lincoln' },
  { name: 'Northwestern University' },
  { name: 'University of Maryland' },
  { name: 'Rutgers University' },
  { name: 'Michigan State University' },
  { name: 'Purdue University' },
  { name: 'University of Illinois at Urbana-Champaign' },
  { name: 'Stanford University' },
  { name: 'University of California, Berkeley' },
  { name: 'University of California, Los Angeles' },
  { name: 'University of Washington' },
  { name: 'University of Oregon' },
  { name: 'Oregon State University' },
  { name: 'Washington State University' },
  { name: 'University of Utah' },
  { name: 'University of Arizona' },
  { name: 'Arizona State University' },
  { name: 'University of Colorado Boulder' },
  { name: 'University of Cincinnati' },
  { name: 'University of Central Florida' },
  { name: 'University of Houston' },
  { name: 'Brigham Young University' },
  { name: 'Texas Christian University' },
  { name: 'Baylor University' },
  { name: 'Texas Tech University' },
  { name: 'Texas A&M University' },
  { name: 'University of Arkansas' },
  { name: 'University of Missouri' },
  { name: 'Mississippi State University' },
  { name: 'University of Mississippi' },
  { name: 'University of South Carolina' },
  { name: 'Vanderbilt University' },
  { name: 'University of Kentucky' },
  { name: 'West Virginia University' },
  { name: 'University of Memphis' },
  { name: 'Tulane University' },
  { name: 'Southern Methodist University' },
  { name: 'United States Naval Academy' },
  { name: 'United States Military Academy' },
  { name: 'United States Air Force Academy' },
  { name: 'Boise State University' },
  { name: 'Fresno State University' },
  { name: 'San Diego State University' },
]

const VOLLEYBALL_D1: College[] = [
  { name: 'University of Texas at Austin' },
  { name: 'Stanford University' },
  { name: 'University of Nebraska–Lincoln' },
  { name: 'University of Wisconsin–Madison' },
  { name: 'Pennsylvania State University' },
  { name: 'University of Minnesota' },
  { name: 'University of Florida' },
  { name: 'University of Louisville' },
  { name: 'University of Pittsburgh' },
  { name: 'University of Kentucky' },
  { name: 'University of Tennessee' },
  { name: 'University of Washington' },
  { name: 'University of Oregon' },
  { name: 'University of California, Los Angeles' },
  { name: 'University of Southern California' },
  { name: 'University of Hawaii at Manoa' },
  { name: 'Brigham Young University' },
  { name: 'Creighton University' },
  { name: 'Marquette University' },
  { name: 'Purdue University' },
  { name: 'The Ohio State University' },
  { name: 'University of Michigan' },
  { name: 'Michigan State University' },
  { name: 'University of Illinois at Urbana-Champaign' },
  { name: 'University of Iowa' },
  { name: 'Northwestern University' },
  { name: 'Indiana University' },
  { name: 'University of Maryland' },
  { name: 'Rutgers University' },
  { name: 'University of San Diego' },
  { name: 'Pepperdine University' },
  { name: 'Loyola Marymount University' },
  { name: 'Long Beach State University' },
  { name: 'California Polytechnic State University' },
  { name: 'University of California, Santa Barbara' },
  { name: 'University of California, San Diego' },
  { name: 'University of California, Irvine' },
  { name: 'University of Utah' },
  { name: 'University of Colorado Boulder' },
  { name: 'University of Arizona' },
  { name: 'Arizona State University' },
  { name: 'Baylor University' },
  { name: 'Texas Tech University' },
  { name: 'Texas Christian University' },
  { name: 'Iowa State University' },
  { name: 'Kansas State University' },
  { name: 'University of Kansas' },
  { name: 'University of Missouri' },
  { name: 'University of Arkansas' },
  { name: 'Auburn University' },
  { name: 'University of Alabama' },
  { name: 'Louisiana State University' },
  { name: 'University of Mississippi' },
  { name: 'University of South Carolina' },
  { name: 'University of Georgia' },
  { name: 'Vanderbilt University' },
  { name: 'Florida State University' },
  { name: 'University of Notre Dame' },
  { name: 'University of North Carolina at Chapel Hill' },
  { name: 'North Carolina State University' },
  { name: 'Wake Forest University' },
  { name: 'Clemson University' },
  { name: 'Duke University' },
  { name: 'Virginia Tech' },
  { name: 'University of Virginia' },
  { name: 'University of Miami' },
  { name: 'Syracuse University' },
  { name: 'Boston College' },
]

const SCHOOLS: Record<SportSlug, College[]> = {
  soccer: SOCCER_D1,
  basketball: BASKETBALL_D1,
  football: FOOTBALL_D1,
  volleyball: VOLLEYBALL_D1,
}

export function getCollegeForSport(sport: SportSlug, queueIndex: number): string {
  const list = SCHOOLS[sport]
  return list[((queueIndex % list.length) + list.length) % list.length].name
}

export function getCollegeListLength(sport: SportSlug): number {
  return SCHOOLS[sport].length
}
