// FUSE-ID Privacy Policy. Bump PRIVACY_VERSION on any material change so
// existing users are re-prompted to accept on their next login.

export const PRIVACY_VERSION = '2025-06-01'
export const PRIVACY_EFFECTIVE_DATE = 'June 1, 2025'

export const PRIVACY_MD = `# Privacy Policy

**Last Updated: ${PRIVACY_EFFECTIVE_DATE}**

FUSE-ID is an AI-powered college athletic recruiting platform. This Privacy Policy explains what information we collect, how we use it, who we share it with, and what choices you have. We handle your data — and the data of the student athletes who use this platform — with care and transparency.

---

## 1. Who This Policy Covers

This Privacy Policy applies to all users of the FUSE-ID platform, including:

- Student athletes who create and maintain recruiting profiles
- Parents and guardians who access read-only board views or shared-account co-editor access
- Visitors to fuse-id.online who have not created an account

If a student athlete is under 13 years of age, we require verifiable parental consent before collecting any personal information, consistent with the Children's Online Privacy Protection Act (COPPA).

---

## 2. Information We Collect

### 2.1 Information You Provide Directly

When you register and use FUSE-ID, you provide us with:

- **Account information:** email address, password (hashed), name, date of birth
- **Athletic profile:** position, club team, competitive level, highlight video URL, height, weight
- **Academic profile:** unweighted GPA, SAT/ACT scores, intended major, high school
- **Recruiting preferences:** division levels of interest, tuition budget, geographic preferences
- **Dream schools and target programs**
- **Coach communications:** contact logs, email subjects, notes, follow-up dates (entered by you)
- **Scholarship offer data:** aid amounts, tuition, decision deadlines
- **Social and contact fields:** Twitter, Instagram, Hudl, YouTube handles (optional)
- **Payment information:** processed securely by Stripe; we do not store credit card numbers
- **Co-owner email:** if a parent signs up and invites their athlete (or vice versa), we collect the second email address to send the invitation

### 2.2 Information Generated by the Platform

Through your use of FUSE-ID, we generate and store:

- Match engine results: scored and ranked program lists, tier classifications
- AI email draft content you generate and optionally save
- AI Profile Tips generated from your profile data
- Token usage logs: match engine runs, email drafts, purchases
- Board activity: status updates, pipeline stage transitions, timestamps

### 2.3 Automatically Collected Information

When you access the Platform, we automatically collect:

- **Log data:** IP address, browser type and version, pages visited, time and date of visits
- **Device information:** operating system, screen resolution, device type
- **Usage analytics:** feature interactions, session duration, funnel progression events

We use standard cookies and local storage to maintain your session and remember preferences such as dark/light mode. We do not use third-party advertising cookies.

---

## 3. How We Use Your Information

We use the information we collect exclusively to operate, improve, and support the Platform.

### 3.1 Core Platform Operations

- Running the AI Match Engine against your profile to produce scored program lists
- Generating personalized coach email drafts using your profile, target program data, and contact history
- Calculating merit aid estimates and net cost projections
- Displaying your recruiting board and communications log
- Managing parent/guardian read-only access tokens and shared-account co-owner invitations
- Processing token and subscription purchases

### 3.2 Platform Improvement

- Analyzing aggregate usage patterns to improve AI scoring models and email generation quality
- Identifying and fixing bugs, performance issues, and data accuracy gaps
- Building and testing new features

When we use profile data to improve AI models, we use aggregated and anonymized data where possible. We do not use individual athlete profiles for commercial purposes outside of operating the Platform.

### 3.3 Communications

- Sending transactional emails: account confirmation, co-owner invite links, parent invite links, password reset
- Sending product updates and feature announcements (you may opt out at any time)
- Responding to support requests

---

## 4. How We Share Your Information

### 4.1 We Do Not Sell Your Data

FUSE-ID does not sell, rent, or trade your personal information or athlete profile data to colleges, universities, coaches, recruiting services, advertisers, or any third party. This is a core principle of our platform and will not change.

### 4.2 Service Providers

We share data with trusted third-party service providers who help us operate the Platform, under strict data processing agreements:

- **Stripe:** payment processing for subscriptions and token packs
- **Supabase:** authentication, database, and storage infrastructure
- **Anthropic (Claude):** powers the match engine and email generation (data sent under data processing agreement; not used to train third-party models)
- **Sentry:** error monitoring and performance tracing
- **Resend:** transactional email delivery

### 4.3 Shared Accounts (Parent + Athlete Co-Editors)

When a parent signs up and invites their athlete (or an athlete invites a parent into a shared account), both co-owners can view and edit all profile data, communications logs, and recruiting board entries. Activity by one co-owner is visible to the other. By accepting a co-owner invitation, both parties consent to this shared visibility.

### 4.4 Read-Only Parent Access

Separately, athletes who own a non-shared account may invite up to two (2) parent or guardian email addresses to view their recruiting board as read-only viewers. Read-only viewers cannot modify any data and their access can be revoked at any time.

### 4.5 Public Profile

If you enable your Public Profile, your recruiting resume becomes accessible to anyone with the link (or via search engine if you elect indexing). Your Public Profile contains the fields you choose to display. You can disable your Public Profile at any time from your Settings page.

### 4.6 Legal Requirements

We may disclose information if required by law, court order, or governmental authority, or if we believe in good faith that disclosure is necessary to protect the safety of any person, prevent fraud, or protect our legal rights.

---

## 5. Children's Privacy (COPPA)

FUSE-ID is designed for use by student athletes, many of whom are minors. We take children's privacy seriously.

- We do not knowingly collect personal information from children under 13 without verifiable parental consent.
- If a user is identified as under 13 without parental consent on file, we will delete their account and associated data promptly.
- Parents or guardians may request access to, correction of, or deletion of their child's account data by contacting us at bryan.fossi@promotedsoccerconsultants.com.
- We do not display advertising on any part of the Platform, including to minors.
- We do not share minor athlete data with colleges, coaches, or commercial third parties.

For users ages 13–17, we apply additional care: we do not use their data for any purpose beyond operating the Platform, and we do not enable public profile indexing by default for accounts flagged as minors.

---

## 6. Data Security

We implement industry-standard security measures to protect your information:

- Passwords are hashed and never stored in plaintext
- All data in transit is encrypted via TLS (HTTPS)
- All data at rest is encrypted in our cloud storage infrastructure
- Co-owner and parent access tokens are time-limited and cryptographically signed
- Payment data is handled exclusively by Stripe and never stored on our servers
- Access to production data is restricted to authorized personnel only

No security system is impenetrable. In the event of a data breach affecting your information, we will notify you in accordance with applicable law.

---

## 7. Data Retention

We retain your data for as long as your account is active and for a reasonable period thereafter. Specifically:

- **Active accounts:** all profile and activity data retained and accessible
- **Deleted accounts:** core profile and communications data deleted within 30 days of account deletion request
- **Payment records:** retained for 7 years as required for tax and legal compliance
- **Anonymized analytics data:** may be retained indefinitely in aggregated form

You may request deletion of your account and all associated personal data at any time from your account settings or by contacting bryan.fossi@promotedsoccerconsultants.com.

---

## 8. Your Rights & Choices

Depending on your location, you may have the following rights regarding your personal data.

### 8.1 Access & Portability

You may request a copy of all personal data we hold about you. We will provide this in a machine-readable format within 30 days of your request.

### 8.2 Correction

You may update or correct your profile data at any time from within the Platform. For data you cannot edit yourself, contact bryan.fossi@promotedsoccerconsultants.com.

### 8.3 Deletion

You may request deletion of your account and personal data. We will honor deletion requests within 30 days, subject to retention obligations described in Section 7.

### 8.4 Opt-Out of Marketing

You may opt out of marketing emails at any time using the unsubscribe link in any such email. Transactional emails (account confirmation, co-owner invites, parent invites, password reset) cannot be opted out of while your account is active.

### 8.5 California Residents

California residents have additional rights under the California Consumer Privacy Act (CCPA), including the right to know, the right to delete, the right to opt-out of sale (we do not sell data), and the right to non-discrimination for exercising these rights. To submit a CCPA request, contact bryan.fossi@promotedsoccerconsultants.com.

---

## 9. Cookies & Tracking

FUSE-ID uses the following types of cookies and local storage:

- **Session cookies:** required to keep you logged in while using the Platform. Cannot be disabled.
- **Preference storage:** saves your dark/light mode preference and other UI settings.
- **Analytics cookies:** anonymized usage tracking to improve the Platform. You may opt out in your browser settings.

We do not use advertising cookies, third-party tracking pixels, or retargeting technologies. There are no ads on FUSE-ID.

---

## 10. Third-Party Links

Your FUSE-ID profile may contain links to third-party services such as Hudl, YouTube, or personal social media accounts. These links direct you to platforms with their own privacy policies. FUSE-ID is not responsible for the privacy practices or content of third-party services.

---

## 11. International Users

FUSE-ID is operated from the United States. If you access the Platform from outside the U.S., your data will be transferred to and processed in the United States. By using the Platform, you consent to this transfer. We apply appropriate safeguards for international transfers consistent with applicable data protection law.

---

## 12. Changes to This Policy

We may update this Privacy Policy from time to time. When we make material changes, we will notify you by email (if you have an account) and by posting a notice on the Platform at least 14 days before the changes take effect. Your continued use of the Platform after the effective date constitutes acceptance of the revised policy.

---

## 13. Contact & Data Requests

For privacy-related questions, data access requests, deletion requests, or parental consent inquiries:

**Privacy Officer** — bryan.fossi@promotedsoccerconsultants.com — fuse-id.online

Response time target: 5 business days for general inquiries; 30 days for formal data requests.
`
